version: 1.0.{build}
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\android-sdk
  AndroidSdkDirectory: C:\android-sdk
  # for msbuild
  JavaSdkDirectory: C:\Program Files (x86)\Java\jdk1.8.0
  
xamarin:
  email: fridayideasgroup@gmail.com
  password:
    secure: 8G7oASWzzzsic0ngACjkHmj9FCR1cpQ+ahZVHH00npg=
  android: true
  ios: true
  
install:
 - ps: $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\xpkg.zip"
 - ps: (New-Object Net.WebClient).DownloadFile('https://components.xamarin.com/submit/xpkg', $zipPath)
 - ps: 7z x $zipPath | Out-Null
 - ps: Set-Content -path "$env:USERPROFILE\.xamarin-credentials" -value "xamarin.com,$env:XAMARIN_COOKIE"
 
before_build:
 - cmd: mklink /j %ANDROID_HOME% "C:\Program Files (x86)\Android\android-sdk"
 # we have to update twice because the first tools update does not expose v7.0 SDKs (at present)
 - cmd: echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools,tools
 - cmd: echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools,tools,android-24
 - nuget restore
 - xamarin-component restore DayTomato.sln

build:
  project: DayTomato.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
after_build:
 - cmd: dir DayTomato\DayTomato.Droid\
 
branches:
  # whitelist
  only:
    - master

artifacts:
- path: DayTomato\DayTomato.Droid\bin\Release\com.fridayideas.daytomato.apk
  name: project
  
deploy:
  release: daytomato$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token: $env:GITHUB_TOKEN    # your encrypted token from GitHub
  artifact: project           # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true
    branch: master 
  
