version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2015
configuration: Release

before_build:
- ps: >-
    nuget install NuProj -Prerelease -OutputDirectory .\packages
    nuget restore .\DayTomato.sln
build:
  project: .\DayTomato.sln
  verbosity: quiet
test: off
