version: 1.0.{build}
nuget:
  account_feed: true
  project_feed: true
xamarin:
  email: jameswoo@uvic.ca
  password:
    secure: /SzUKiO5Vi5nkyZ6e9YovA==
  android: true
  ios: true
before_build:
  - nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
