version: 1.0.{build}
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\android-sdk
  AndroidSdkDirectory: C:\android-sdk

xamarin:
  email: fridayideasgroup@gmail.com
  password:
    secure: 8G7oASWzzzsic0ngACjkHmj9FCR1cpQ+ahZVHH00npg=
  android: true
  ios: true

build_script:
 - cmd: mklink /j %ANDROID_HOME% "C:\Program Files (x86)\Android\android-sdk"
 - cmd: echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools,tools,android-23,android-19

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
 
branches:
  # whitelist
  only:
    - master

deploy:
  release: daytomato$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: $env:GITHUB_TOKEN    # your encrypted token from GitHub
  artifact: '*.nupkg'            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
  
